//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::prototype3::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::prototype3::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->prevButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->prevButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::prototype3::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PrevButton_Click);
        }
        break;
    case 3:
        {
            this->reloadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->reloadButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::prototype3::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ReloadButton_Click);
        }
        break;
    case 4:
        {
            this->urlContainer = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->urlContainer))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::prototype3::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&MainPage::UrlContainer_KeyDown);
        }
        break;
    case 5:
        {
            this->loaderRing = safe_cast<::Windows::UI::Xaml::Controls::ProgressRing^>(__target);
        }
        break;
    case 6:
        {
            this->outputBox = safe_cast<::Windows::UI::Xaml::Controls::WebView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(this->outputBox))->NavigationStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationStartingEventArgs^>(this, (void (::prototype3::MainPage::*)
                (::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationStartingEventArgs^))&MainPage::OutputBox_NavigationStarting);
            (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(this->outputBox))->ContentLoading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewContentLoadingEventArgs^>(this, (void (::prototype3::MainPage::*)
                (::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewContentLoadingEventArgs^))&MainPage::OutputBox_ContentLoading);
            (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(this->outputBox))->NavigationCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationCompletedEventArgs^>(this, (void (::prototype3::MainPage::*)
                (::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationCompletedEventArgs^))&MainPage::OutputBox_NavigationCompleted);
            (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(this->outputBox))->NavigationFailed += ref new ::Windows::UI::Xaml::Controls::WebViewNavigationFailedEventHandler(this, (void (::prototype3::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::WebViewNavigationFailedEventArgs^))&MainPage::OutputBox_NavigationFailed);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::prototype3::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


