#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
                ref class ProgressRing;
                ref class WebView;
            }
        }
    }
}

namespace prototype3
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Button^ prevButton;
        private: ::Windows::UI::Xaml::Controls::Button^ reloadButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ urlContainer;
        private: ::Windows::UI::Xaml::Controls::ProgressRing^ loaderRing;
        private: ::Windows::UI::Xaml::Controls::WebView^ outputBox;
    };
}

